version: '3'

services:
  web:
    build: .
    command: gunicorn your_project_name.wsgi:application -b 0.0.0.0:7000
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: btredb-container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
