version: '3'

services:
  web:
    image: dudosart/btre-pro
    ports:
      - "8080:7000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: btredb-container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
